[build]
builder = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
PYTHONPATH = "/app"
